[tool.poetry]
name = "fastui-tutorials"
version = "0.1.0"
description = "I'm exploring the capabilities of FastUI."
authors = ["Hasan Sezer Taşan <hasansezertasan@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<3.12"
fastui = "^0.5.2"
fastapi = { extras = ["all"], version = "^0.110.0" }
typer = { extras = ["all"], version = "^0.9.0" }
SQLAlchemy = { extras = ["aiosqlite", "asyncio"], version = "2.0.28" }

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.0"
mypy = ">=1.0.0"
ruff = "==0.3.3"
pre-commit = ">=2.20.0, <4.0.0"
[tool.poetry.group.test.dependencies]
pytest = "^8.1.1"

[tool.ruff]
# Exclude a variety of commonly ignored directories.
exclude = [
  ".bzr",
  ".direnv",
  ".eggs",
  ".git",
  ".git-rewrite",
  ".hg",
  ".ipynb_checkpoints",
  ".mypy_cache",
  ".nox",
  ".pants.d",
  ".pyenv",
  ".pytest_cache",
  ".pytype",
  ".ruff_cache",
  ".svn",
  ".tox",
  ".venv",
  ".vscode",
  "__pypackages__",
  "_build",
  "buck-out",
  "build",
  "dist",
  "node_modules",
  "site-packages",
  "venv",
  "alembic",
  "migrations",
]

# Same as Black.
line-length = 88
indent-width = 4

# Assume Python 3.8
target-version = "py38"

# Extra
show-fixes = true
extend-include = ["*.ipynb"]
fix = true

[tool.ruff.lint]
# Run `ruff linter` command to see all available linters and their descriptions
select = [
  # All Available Linters
  "F", # Pyflakes
  # "E/W", # pycodestyle
  # Custom Start
  "E",  # pycodestyle errors
  "E4",
  "E7",
  "E9",
  "W",  # pycodestyle warnings
  # Custom End
  "C90", # mccabe
  "I",   # isort
  "N",   # pep8-naming
  # "D", # pydocstyle
  "UP",  # pyupgrade
  "YTT", # flake8-2020
  "ANN", # flake8-annotations
  # "ASYN", #C flake8-async
  "TRIO", # flake8-trio
  # "S", # flake8-bandit
  "BLE", # flake8-blind-except
  "FBT", # flake8-boolean-trap
  "B",   # flake8-bugbear
  # Custom Start
  "B9",
  # Custom End
  "A", # flake8-builtins
  # "COM", # flake8-commas
  "CPY", # flake8-copyright
  "C4",  # flake8-comprehensions
  # Custom Start
  "C", # flake8-comprehensions
  # Custom End
  "DTZ", # flake8-datetimez
  "T10", # flake8-debugger
  "DJ",  # flake8-django
  "EM",  # flake8-errmsg
  "EXE", # flake8-executable
  # "FA", # flake8-future-annotations
  # "ISC",  # flake8-implicit-str-concat
  "ICN", # flake8-import-conventions
  "G",   # flake8-logging-format
  # "INP",  # flake8-no-pep420
  "PIE",  # flake8-pie
  "T20",  # flake8-print
  "PYI",  # flake8-pyi
  "PT",   # flake8-pytest-style
  "Q",    # flake8-quotes
  "RSE",  # flake8-raise
  "RET",  # flake8-return
  "SLF",  # flake8-self
  "SLOT", # flake8-slots
  "SIM",  # flake8-simplify
  "TID",  # flake8-tidy-imports
  # "TCH",  # flake8-type-checking
  "INT", # flake8-gettext
  "ARG", # flake8-unused-arguments
  "PTH", # flake8-use-pathlib
  "TD",  # flake8-todos
  "FIX", # flake8-fixme
  # "ERA", # eradicate
  "PD",   # pandas-vet
  "PGH",  # pygrep-hooks
  "PL",   # Pylint
  "TRY",  # tryceratops
  "FLY",  # flynt
  "NPY",  # NumPy-specific rules
  "AIR",  # Airflow
  "PERF", # Perflint
  "FURB", # refurb
  "LOG",  # flake8-logging
  "RUF",  # Ruff-specific rules
]
ignore = [
  "A002", # Argument `id` is shadowing a Python builtin
  "B008", # do not perform function calls in argument defaults
  # "C901", # too complex
  "E501", # line too long, handled by black
  # "F401", # imported but unused
  # "E402", # module level import not at top of file
  "E712", # comparison to True should be 'if cond is True:' or 'if cond:'
  "F821", # undefined name
  # "W191", # indentation contains tabs
  # "E101", # indentation contains mixed spaces and tabs
  # "C408", # Unnecessary list comprehension - rewrite as a for loop
]
# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []
# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Extra
preview = true
ignore-init-module-imports = true

[tool.ruff.lint.flake8-copyright]
author = "Hasan Sezer Taşan <hasansezertasan@gmail.com>"

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

# Enable auto-formatting of code examples in docstrings. Markdown,
# reStructuredText code/literal blocks and doctests are all supported.
#
# This is currently disabled by default, but it is planned for this
# to be opt-out in the future.
docstring-code-format = true

# Set the line length limit used when formatting code snippets in
# docstrings.
#
# This only has an effect when the `docstring-code-format` setting is
# enabled.
docstring-code-line-length = "dynamic"

[tool.ruff.lint.pydocstyle]
convention = "google"
