---
name: CI
on:
  workflow_dispatch: # Allows manual triggering of the workflow
  pull_request:
    branches: ["main"] # Triggers on pull requests targeting the main branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }} # Grouping by workflow name and reference
  cancel-in-progress: true # Cancel any in-progress runs for the same group
jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version-file: ".python-version"
      - name: Setup uv
        id: setup-uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
        with:
          enable-cache: true
      - name: Restore cache
        if: steps.setup-uv.outputs.cache-hit == 'true'
        run: echo "Cache was restored"
      - name: Sync
        run: uv sync --locked --all-groups --all-packages
      - name: Checks
        run: |
          uv run --locked validate-pyproject pyproject.toml
          uv run --locked codespell .
          uv run --locked vulture .
          uv run --locked ruff check --output-format=github
          uv run --locked taplo lint pyproject.toml
          uv run --locked ruff format --check
          uv run --locked taplo format --check pyproject.toml
          uv run --locked pytest -q
